server:
  tomcat:
    max-http-form-post-size: -1 #解除tomcat的大小限制，-1表示无限制
  port: 8089
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/crm?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root2019
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath*:mappers/*.xml
  type-aliases-package: com.crm.springbootcrm.pojos
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
