server:
  tomcat:
    max-http-form-post-size: -1
  port: 8089
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://rm-bp1fv4f328bk6p3zoro.mysql.rds.aliyuncs.com:3306/smart_pension?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: wp
    password: Abc123456
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath*:mappers/**/*.xml
  type-aliases-package: com.example.smartpensionspringboot.*.pojos, com.example.smartpensionspringboot.*.vo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
